graphql:
  servlet:
    maxQueryDepth: 100
    exception-handlers-enabled: true
  playground:
    headers:
      Authorization: Bearer Token
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
